/* Definitieve reisbasis van Ruben en Martine; spoor27 blijft het oorspronkelijke vergelijkingsscenario. */
window.CHINA2027 = {
  checked: "2026-09-30",
  flightTotal: 1671.68,
  stays: [
    {
      id: "shanghai",
      budget: {
        hotel: "Campanile Shanghai Bund",
        area: "Huangpu / Bund en Yu Garden",
        room: "King / Twin · babybed en kameroppervlak navragen",
        low: 50,
        high: 75,
        url: "https://shanghai-bund.campanile.com/en-us/",
        why: "Een compactere stadsbasis bij de Bund, met een lager kamerbudget.",
        check:
          "Vroege check-in, babybed, rookvrije kamer en totale prijs voor twee volwassenen + baby bevestigen.",
      },
      name: "Shanghai",
      cn: "上海",
      start: 2,
      nights: 3,
      lat: 31.2304,
      lng: 121.4737,
      hotel: "Pullman Shanghai Central",
      room: "Superior King · 48 m²",
      area: "Huangpu / voormalige Franse Concessie",
      low: 100,
      high: 155,
      url: "https://pullman.accor.com/en/hotels/shanghai/7298/rooms.html",
      why: "Een ruime eerste basis om te landen, met plek voor een babybed en de buggy.",
      check:
        "Babybed, rustige rookvrije kamer en vroege toegang na aankomst om 06:30 schriftelijk aanvragen. Gegarandeerde vroege check-in kan een extra nacht kosten.",
      highlight: "De Bund, tuinen en een eerste kom noedels.",
      image: "shanghai",
    },
    {
      id: "hangzhou",
      budget: {
        hotel: "Holiday Inn Express Hangzhou Westlake East",
        area: "Westlake Avenue / bij Hangzhou Railway Station",
        room: "Standard King · babybed op aanvraag",
        low: 45,
        high: 70,
        url: "https://www.ihg.com/holidayinnexpress/hotels/us/en/hangzhou/hghwe/hoteldetail",
        why: "Praktische ketenbasis; voor West Lake een korte rit plannen in plaats van het Kerry Centre-budget.",
        check:
          "Niet verwarren met Hangzhou East station. Ontbijt, babybed en eventuele 6% btw controleren.",
      },
      name: "Hangzhou",
      cn: "杭州",
      start: 5,
      nights: 2,
      lat: 30.25,
      lng: 120.149,
      hotel: "Midtown Shangri-La, Hangzhou",
      room: "Deluxe King · kamertype bevestigen",
      area: "Kerry Centre / West Lake",
      low: 130,
      high: 185,
      url: "https://www.shangri-la.com/hangzhou/midtownshangrila/",
      why: "West Lake op loopafstand: fijn voor korte wandelingen en terug naar de kamer tijdens het dutje.",
      check:
        "Babybed en rookvrije kamer aanvragen. Ontbijt, totale kamerprijs en annuleringsvoorwaarden controleren.",
      highlight: "Van skyline naar theegroene heuvels.",
    },
    {
      id: "beijing",
      budget: {
        hotel: "Citytel Inn",
        area: "Nanheyan / Dongcheng, nabij Wangfujing",
        room: "Double · ruimte voor babybed nog bevestigen",
        low: 55,
        high: 85,
        url: "https://www.trip.com/hotels/beijing-hotel-detail-436626/citytel-inn/",
        why: "Centrale eenvoud: minder kamercomfort, dezelfde vier nachten voor de belangrijkste uitstappen.",
        check:
          "Babybed en kameroppervlak schriftelijk bevestigen; Qingming kan de raming verhogen.",
      },
      name: "Beijing",
      cn: "北京",
      start: 7,
      nights: 4,
      lat: 39.916,
      lng: 116.412,
      hotel: "Park Plaza Beijing Wangfujing",
      room: "Superior / Deluxe · ruimte voor babybed navragen",
      area: "Wangfujing / Dongcheng",
      low: 100,
      high: 165,
      url: "https://www.radissonhotels.com/en-us/hotels/park-plaza-beijing-wangfujing",
      why: "Centrale uitvalsbasis voor de keizerstad, zonder iedere dag van hotel te wisselen.",
      check:
        "Babybed, rustige kamer en privétransfer naar Mutianyu met passend kinderzitje bevestigen. Qingming kan prijzen en drukte verhogen.",
      highlight: "Keizerlijke daken. Een muur tot aan de horizon.",
    },
    {
      id: "xian",
      budget: {
        hotel: "Campanile Xi’an Bell Tower Huimin Street",
        area: "Binnen de stadsmuur / Bell Tower",
        room: "King / Twin · kamertype bevestigen",
        low: 35,
        high: 55,
        url: "https://www.booking.com/hotel/cn/campanile-xian-bell-tower.html",
        why: "Eenvoudige centrale hotelkeuze bij de torens; het boutiquehotel blijft ernaast beschikbaar.",
        check:
          "Babybed, lift, rookvrije kamer en definitieve gezinsprijs bevestigen.",
      },
      name: "Xi’an",
      cn: "西安",
      start: 11,
      nights: 2,
      lat: 34.253,
      lng: 108.943,
      hotel: "Eastern House Boutique Hotel",
      room: "King / Twin · kamertype controleren",
      area: "Binnen de stadsmuur / Beilin",
      low: 70,
      high: 110,
      url: "https://www.eastern-house.cn/en/",
      why: "Een centrale boutique-basis voor het Terracottaleger en een korte avondwandeling.",
      check:
        "Vraag naar babybed, rustige verdieping en een chauffeur met kinderzitje voor de museumdag.",
      highlight: "Een leger van klei, een stad vol verhalen.",
    },
    {
      id: "chengdu",
      budget: {
        hotel: "Holiday Inn Express Chengdu Tianfu Square",
        area: "Tianfu Square / stadscentrum",
        room: "Standard King · babybed navragen",
        low: 40,
        high: 65,
        url: "https://www.ihg.com/holidayinnexpress/hotels/us/en/chengdu/ctuts/hoteldetail",
        why: "Een gewone hotelkamer als voordeliger alternatief voor het Somerset-appartement.",
        check:
          "Babybed en ontbijt bevestigen; voor wasgoed een wasserette of hotelservice plannen.",
      },
      name: "Chengdu",
      cn: "成都",
      start: 13,
      nights: 3,
      lat: 30.647,
      lng: 104.065,
      hotel: "Somerset Riverview Chengdu",
      room: "Appartement · indeling en wasfaciliteiten navragen",
      area: "Jinjiang-rivier / Wuhou",
      low: 65,
      high: 105,
      url: "https://www.discoverasr.com.cn/somerset-serviced-residence/china/somerset-riverview-chengdu",
      why: "Een appartement is prettig voor een wasmoment, eenvoudige maaltijden en drie ontspannen nachten.",
      check:
        "Vraag naar een aparte slaapruimte, eigen wasmachine, babybed en de rit naar de Panda Base.",
      highlight: "Panda’s in de ochtend. Thee in de middag.",
    },
    {
      id: "chongqing",
      budget: {
        hotel: "Mercure Chongqing Downtown",
        area: "Jiefangbei / Yuzhong",
        room: "Standard King · kamertype bevestigen",
        low: 50,
        high: 80,
        url: "https://all.accor.com/hotel/B330/index.es.shtml",
        why: "Een centrale overnachting voor Hongya Dong zonder de voco-kamerprijs.",
        check:
          "Babybed, beide stationstransfers en rookvrije kamer vooraf bevestigen.",
      },
      name: "Chongqing",
      cn: "重庆",
      start: 16,
      nights: 1,
      lat: 29.563,
      lng: 106.584,
      hotel: "voco Chongqing Chaotianmen",
      room: "Standard / Premium · rivierzicht optioneel",
      area: "Chaotianmen / Yuzhong",
      low: 95,
      high: 155,
      url: "https://www.ihg.com/voco/hotels/gb/en/chongqing/ckgct/hoteldetail",
      why: "De enige korte stop: comfortabel inchecken en ’s avonds even naar de verlichte rivierstad.",
      check:
        "Beide stationstransfers vastleggen, inclusief exact station, kinderzitje en de volgende ochtend vertrektijd.",
      highlight: "Een futuristische stad die ’s avonds aangaat.",
    },
    {
      id: "zhangjiajie",
      budget: {
        hotel: "Maosao Inn",
        area: "Wulingyuan / Wuling Road",
        room: "Double · babybed en toegang navragen",
        low: 35,
        high: 60,
        url: "https://www.trip.com/hotels/zhangjiajie-hotel-detail-3000682/maosao-inn/",
        why: "Kleine accommodatie in Wulingyuan; vier nachten en de weerbuffer blijven behouden.",
        check:
          "Lift/trappen, babybed, verwarming, rookvrije kamer en rit naar de parkingang bevestigen.",
      },
      name: "Wulingyuan",
      cn: "武陵源",
      start: 17,
      nights: 4,
      lat: 29.347,
      lng: 110.551,
      hotel: "Hampton by Hilton Zhangjiajie National Forest Park",
      room: "King · babybed op aanvraag",
      area: "Wulingyuan / oostelijke parkingang",
      low: 80,
      high: 130,
      url: "https://www.hilton.com/en/hotels/dygzjhx-hampton-zhangjiajie-national-forest-park/",
      why: "Volgens Hilton circa 500 meter van de oostelijke ticketingang. Vier nachten geven ruimte om de bergdagen op het weer af te stemmen.",
      check:
        "Niet verwarren met de Hampton bij Tianmen in de stad. Transfer Zhangjiajie West–Wulingyuan en eventuele Tianmen-dag vooraf regelen.",
      highlight: "Vier nachten tussen de Avatarbergen.",
      image: "zhangjiajie",
    },
    {
      id: "yangshuo",
      budget: {
        hotel: "Yangshuo River View Hotel",
        area: "Yangshuo-centrum / Li River",
        room: "Double · rustige kamer navragen",
        low: 40,
        high: 65,
        url: "https://www.booking.com/hotel/cn/yang-shuo-wang-jiang-lou-jiu-dian.de.html",
        why: "Een stadsbasis aan de Li River; voordeliger, maar voor Yulong River een transfer nodig.",
        check:
          "Babybed, lift en stilte in de avond bevestigen. Dit hotel ligt niet aan de Yulong.",
      },
      name: "Yangshuo",
      cn: "阳朔",
      start: 21,
      nights: 4,
      lat: 24.748,
      lng: 110.45,
      hotel: "Yangshuo Mountain Retreat",
      room: "Riverview / Family · kamertype navragen",
      area: "Yulong River / buiten het centrum",
      low: 80,
      high: 135,
      url: "https://www.yangshuomountainretreat.com/",
      why: "Slapen bij de rivier en het landschap: hier mag het tempo vier nachten omlaag.",
      check:
        "Babybed, trapvrije bereikbaarheid, transfers en eetmogelijkheden vragen. Water dichtbij: Amélie steeds onder toezicht.",
      highlight: "Karstbergen, rivierlicht en nergens haast.",
      image: "yangshuo",
    },
    {
      id: "longji",
      budget: {
        hotel: "Longji Holiday Hotel",
        area: "Ping’an Village / rijstterrassen",
        room: "Double · kamertype bevestigen",
        low: 30,
        high: 50,
        url: "https://www.booking.com/hotel/cn/longji-holiday.en-gb.html",
        why: "Eenvoudiger slapen in hetzelfde bergdorp, met behoud van twee nachten in de terrassen.",
        check:
          "Portier, trappen, babybed, verwarming en vervoer voor bagage vooraf bevestigen.",
      },
      name: "Longji / Ping’an",
      cn: "龙脊 · 平安",
      start: 25,
      nights: 2,
      lat: 25.755,
      lng: 110.133,
      hotel: "Longji One Art Hotel",
      room: "Double / Family · verwarming navragen",
      area: "Ping’an-dorp / rijstterrassen",
      low: 70,
      high: 115,
      url: "https://www.booking.com/hotel/cn/long-ji-the-one.nl.html",
      why: "Twee nachten midden in het terraslandschap, met tijd voor korte wandelingen.",
      check:
        "Trappen naar het hotel: portier, bagagevervoer, laatste looptraject en kinderbed bevestigen. Houd de grote koffer zo mogelijk bij de chauffeur of in opslag.",
      highlight: "Wakker worden boven de rijstterrassen.",
    },
    {
      id: "hongkong",
      budget: {
        hotel: "B P International",
        area: "Tsim Sha Tsui / bij Kowloon Park",
        room: "City Vista · babybed en ruimte navragen",
        low: 90,
        high: 140,
        url: "https://www.bpih.com.hk/accommodation",
        why: "Een praktische Kowloon-basis als alternatief voor de grotere Salon-kamer bij Eaton.",
        check:
          "Babybed, bagageopslag, kamerruimte en totaal inclusief 10% service en 3% hotelbelasting bevestigen.",
      },
      name: "Hongkong",
      cn: "香港",
      start: 27,
      nights: 3,
      lat: 22.307,
      lng: 114.171,
      hotel: "Eaton HK",
      room: "Salon · circa 28 m²",
      area: "Jordan / Kowloon",
      low: 140,
      high: 220,
      url: "https://www.eatonworkshop.com/en-us/hong-kong/",
      why: "Een leuke, praktische Kowloon-basis met eetmogelijkheden en meer ruimte in een Salon-kamer.",
      check:
        "Babybed, bagageopslag op 26 april, dagkamer of late checkout aanvragen. Controleer of 10% servicekosten en 3% accommodation tax in de getoonde prijs zitten.",
      highlight: "Nog één skyline. En dan samen naar huis.",
    },
  ],
  trains: [
    {
      day: 5,
      from: "Shanghai Hongqiao 上海虹桥",
      to: "Hangzhou East 杭州东",
      time: "0u45–1u15",
      low: 8,
      high: 15,
      note: "Zoek op Hongqiao, niet op het centrale Shanghai-station. Na de trein een korte hoteltransfer.",
    },
    {
      day: 7,
      from: "Hangzhou East 杭州东",
      to: "Beijing South 北京南",
      time: "4u45–6u30",
      low: 75,
      high: 110,
      note: "Voorkeur: rechtstreekse ochtendtrein. Extra drukte rond Qingming; boek bij opening.",
    },
    {
      day: 11,
      from: "Beijing West 北京西",
      to: "Xi’an North 西安北",
      time: "4u10–6u",
      low: 60,
      high: 90,
      note: "Let op: vertrek waarschijnlijk vanaf Beijing West, dus een ander station dan bij aankomst.",
    },
    {
      day: 13,
      from: "Xi’an North 西安北",
      to: "Chengdu East 成都东",
      time: "3u–4u30",
      low: 30,
      high: 45,
      note: "Directe HSR als basis; station en vertrektijd op het boekbare schema bevestigen.",
    },
    {
      day: 16,
      from: "Chengdu East 成都东",
      to: "Chongqing · station te bepalen",
      time: "1u–2u",
      low: 12,
      high: 30,
      note: "Chongqing North, West of East kan per trein verschillen. Chauffeur krijgt het exacte station op het ticket.",
    },
    {
      day: 17,
      from: "Chongqing · station te bepalen",
      to: "Zhangjiajie West 张家界西",
      time: "2u–3u30",
      low: 25,
      high: 45,
      note: "Het vertrekstation hangt af van de dienst. Daarna circa 45–75 minuten privétransfer naar Wulingyuan.",
    },
    {
      day: 21,
      from: "Zhangjiajie West 张家界西",
      to: "Guilin · station te bepalen",
      time: "6u–8u30",
      low: 45,
      high: 75,
      note: "Lange dag: rechtstreekse dienst eerst zoeken; anders met ruime overstap via Changsha South. Daarna circa 1u30–2u naar het gekozen hotel in Yangshuo. 2027-verbinding nog vast te stellen.",
    },
    {
      day: 27,
      from: "Guilin West 桂林西",
      to: "Hong Kong West Kowloon 香港西九龙",
      time: "circa 3u10–3u20",
      low: 40,
      high: 65,
      note: "Voorkeur: rechtstreekse HSR. De route bestaat in het huidige netwerk; duur en dienst in 2027 bevestigen. Guangzhou alleen als terugvaloptie. Na aankomst grensformaliteiten en hoteltransfer.",
    },
  ],
  days: [
    {
      d: 1,
      city: "reis",
      kind: "vlucht",
      title: "De reis begint.",
      sub: "Amsterdam · Zürich · Shanghai",
      am: "Rond 06:50 op Schiphol als werkmarge. SWISS vertrekt om 09:50 uit AMS; paspoorten, babyspullen en kinderzitje bij de hand.",
      pm: "Overstap in Zürich. Exacte aansluiting, terminal en overstaptijd controleren op de vluchtbevestiging.",
      eve: "Nachtvlucht naar Shanghai. Eigen stoel voor Amélie met een voor alle uitvoerende maatschappijen bevestigd vliegtuiggeschikt zitje.",
      baby: "Reserveer de eigen stoel vóór het kiezen van zitplaatsen. Het SWISS-bassinet is bij bijna 11 maanden geen optie.",
      backup:
        "Een ruime overstap en reservekleding voor alle drie in de handbagage.",
      reserve:
        "Eigen stoel, zitje en zitplaatsen op beide SWISS-segmenten schriftelijk bevestigen.",
      cost: "Vluchten: werkelijk betaalde gezinsprijs invullen bij Budget.",
      sleep: "In het vliegtuig",
    },
    {
      d: 2,
      city: "shanghai",
      kind: "rust",
      title: "Hallo Shanghai. Vandaag alleen landen.",
      sub: "Aankomst PVG 06:30 · rustdag",
      am: "Landen om 06:30 lokale tijd. Immigratie, bagage en vooraf geregelde transfer naar het hotel; geen sightseeing-afspraak.",
      pm: "Rust, douchen en een eerste dutje. Vroege check-in aanvragen; boek desgewenst een extra nacht als toegang tot de kamer gegarandeerd moet zijn.",
      eve: "Een korte wandeling in de buurt, makkelijk eten en vroeg terug.",
      baby: "De klok staat zes uur later dan in Nederland. Houd het ritme soepel en plan geen lange wandeling.",
      backup: "Alleen het hotel is vandaag al een goed programma.",
      reserve:
        "PVG-transfer met passend kinderzitje en vroege kamer gereedmaken.",
      cost: "Transfer €50–85 per auto als budget; vroege check-in apart.",
    },
    {
      d: 3,
      city: "shanghai",
      kind: "cultuur",
      title: "Yu Garden & de Bund.",
      sub: "Oud Shanghai, nieuwe skyline",
      am: "Rond 09:00 naar Yu Garden. Bezoek de tuin op rustig tempo; neem een draagzak mee voor smalle paadjes en trappen.",
      pm: "Lunch en dutje in het hotel. Daarna een korte wandeling over de Bund.",
      eve: "Als er energie is: skyline bij het blauwe uur. Anders vroeg eten dichtbij het hotel.",
      baby: "Vandaag twee korte blokken, met een echte pauze ertussen. De buggy is fijn op de Bund.",
      backup:
        "Bij regen: een overdekte lunch en een korte Bund-wandeling zodra het droog wordt.",
      reserve:
        "Yu Garden openingstijden en eventueel ticket vooraf controleren.",
      cost: "Activiteitenpot €15–30 voor twee volwassenen, exclusief eten en lokaal vervoer.",
    },
    {
      d: 4,
      city: "shanghai",
      kind: "keuze",
      title: "Hoog boven de stad. Of een waterdorp.",
      sub: "Shanghai Tower óf Zhujiajiao",
      am: "Keuze A: Shanghai Tower bij goed zicht. Keuze B: privétransfer naar Zhujiajiao voor bruggen, kanalen en thee.",
      pm: "Kies één uitstap. Tower laat ruimte voor een hotelpauze; maak Zhujiajiao bewust een korte dagtrip.",
      eve: "Laatste avond Shanghai: eten in de buurt en rustig inpakken voor de trein.",
      baby: "Draagzak voor bruggen in Zhujiajiao; geen uitgebreid bootprogramma als vaste afspraak.",
      backup:
        "Bij slecht zicht of weinig energie: Franse Concessie, café en hotel.",
      reserve:
        "Uitzichtticket pas na weercheck; bij Zhujiajiao transfer met kinderzitje.",
      cost: "Tower circa €45–65 voor twee; waterdorp met privéauto circa €100–160 als budget.",
    },
    {
      d: 5,
      city: "hangzhou",
      kind: "trein",
      title: "Per spoor naar het West Lake.",
      sub: "Shanghai Hongqiao · Hangzhou East",
      am: "Uitchecken en naar Shanghai Hongqiao. Mik op 60–90 minuten stationsmarge met Amélie.",
      pm: "HSR naar Hangzhou East, hoteltransfer en inchecken. Laat de middag open.",
      eve: "Als het uitkomt: even langs het West Lake wandelen en vroeg eten.",
      baby: "Houd fles, luiers, doekjes en een kleine snacktas buiten de grote koffer.",
      backup:
        "Regen? Geen meerwandeling nodig: hotel en restaurant zijn genoeg.",
      reserve:
        "Treinticket vanaf 18 maart; exacte vrijgavetijd van het vertrekstation controleren.",
      cost: "Trein €8–15 per volwassene; transfer en hotel apart.",
    },
    {
      d: 6,
      city: "hangzhou",
      kind: "cultuur",
      title: "Thee, tempels & een meer.",
      sub: "West Lake · Longjing · Lingyin",
      am: "Rustige wandeling aan West Lake. Kies daarna Longjing-theevelden óf Lingyin als hoofdbezoek.",
      pm: "Na lunch een hotelpauze. Het tweede bezoek alleen toevoegen als iedereen energie heeft; niet alle drie locaties achter elkaar afwerken.",
      eve: "Diner rond het meer of dicht bij het hotel.",
      baby: "Theevelden en tempels hebben trappen: draagzak mee. Geef het dutje de beste plek in de dag.",
      backup: "Bij veel regen: theehuis, korte oeverwandeling en rust.",
      reserve:
        "Voor Lingyin de officiële actuele entree- en reserveringsregels laten controleren door het hotel.",
      cost: "Activiteiten €20–45 voor twee; privévervoer optioneel.",
    },
    {
      d: 7,
      city: "beijing",
      kind: "trein",
      title: "Op naar de keizerstad.",
      sub: "Hangzhou East · Beijing South",
      am: "Ontbijt, uitchecken en vroege hoteltransfer naar Hangzhou East. Een rechtstreekse HSR heeft de voorkeur.",
      pm: "Treinreis circa 4u45–6u30. Lunch, dutje en korte loopmomenten in het rijtuig.",
      eve: "Aankomst Beijing South, transfer en inchecken. Eten in de buurt; geen hutongtour vastzetten.",
      baby: "Stoelen naast elkaar aanvragen. Een eigen stoel voor Amélie kan via een betaald kinderticket; voorwaarden vooraf navragen.",
      backup: "Als aankomst later wordt: alleen naar het hotel.",
      reserve:
        "Trein vanaf 20 maart; Qingming maakt deze periode extra boekingsgevoelig.",
      cost: "Trein €75–110 per volwassene.",
    },
    {
      d: 8,
      city: "beijing",
      kind: "cultuur",
      title: "Door de poorten van de Verboden Stad.",
      sub: "Forbidden City · Jingshan",
      am: "Bezoek de Verboden Stad met een bevestigd tijdslot en dezelfde originele paspoorten als bij de reservering. Start via de zuidelijke toegang volgens ticketinstructies.",
      pm: "Eenvoudige lunch. Jingshan alleen als er energie is: voor het uitzicht moet je omhoog; anders terug naar het hotel.",
      eve: "Rustig diner. Hotel laat de Mutianyu-transfer voor morgen nogmaals bevestigen.",
      baby: "Maak een verkorte route door de paleiscomplexen. Niet elk paviljoen hoeft vandaag.",
      backup:
        "Geen ticket? Vandaag park/hutongs, en alleen naar een andere open dag schuiven als daar tickets beschikbaar zijn.",
      reserve:
        "Boekingsvenster: 28 maart om 20:00 Beijing / 14:00 Nederland. Jullie zijn dan op reis: regel vooraf toegang en hulp bij boeken.",
      cost: "Activiteitenpot €20–35 voor twee, inclusief eventuele extra paleiszalen.",
    },
    {
      d: 9,
      city: "beijing",
      kind: "natuur",
      title: "Een muur tot aan de horizon.",
      sub: "Mutianyu Great Wall · Qingming",
      am: "Vroege privétransfer naar Mutianyu, circa 1u30–2u per richting afhankelijk van verkeer. Kies de gesloten kabelbaan en een kort traject op de muur.",
      pm: "Lunch en terug naar Beijing. Reken op trappen, hellingen en wachtrijen; stop ruim vóór het op is.",
      eve: "Een rustige avond in het hotel.",
      baby: "Draagzak essentieel. Geen buggy op de muur en geen rodelbaan met Amélie.",
      backup:
        "Bij slecht weer of extreme drukte een parkdag. Eventueel ruilen met D10 als tickets en chauffeur dat toelaten.",
      reserve:
        "Kabelbaan/entree en chauffeur vooraf regelen. Qingming op 5 april: definitief vakantieblok 2027 nog controleren.",
      cost: "Privéauto + entree/kabelbaan €140–220 voor het gezin als budget.",
    },
    {
      d: 10,
      city: "beijing",
      kind: "cultuur",
      title: "Tempels in het groen.",
      sub: "Temple of Heaven · Summer Palace optioneel",
      am: "Temple of Heaven: park en hoofdcomplex op rustig tempo.",
      pm: "Hotelpauze. Summer Palace alleen met voldoende energie: het ligt aan de andere kant van de stad. Kies anders één mooie Beijing-dag in plaats van twee grote bezoeken.",
      eve: "Eten, spullen bij elkaar en vertrekstation voor morgen controleren.",
      baby: "De grote parken zijn fijn met buggy; tempeldelen en heuvels vragen een draagzak.",
      backup:
        "Summer Palace vervalt als eerste bij regen, file of slaaptekort.",
      reserve:
        "Actuele entreeregels checken; chauffeur nodig als beide locaties gewenst zijn.",
      cost: "Activiteiten €25–45 voor twee; vervoer apart.",
    },
    {
      d: 11,
      city: "xian",
      kind: "trein",
      title: "Van keizerstad naar zijderoute.",
      sub: "Beijing West · Xi’an North",
      am: "Uitchecken en naar Beijing West. Controleer het station: niet automatisch terug naar Beijing South.",
      pm: "HSR naar Xi’an North, circa 4u10–6u. Privétransfer naar het hotel binnen de stadsmuur.",
      eve: "Eten vlakbij. Alleen een klein rondje als iedereen nog zin heeft.",
      baby: "Geen stadsmuurwandeling als vaste afspraak op een treindag.",
      backup: "Bij vertraging direct hotel en roomservice.",
      reserve: "Treintickets vanaf 24 maart; aankomsttransfer vooraf.",
      cost: "Trein €60–90 per volwassene.",
    },
    {
      d: 12,
      city: "xian",
      kind: "cultuur",
      title: "Oog in oog met het Terracottaleger.",
      sub: "Een halve dag vol verwondering",
      am: "Vroeg met chauffeur naar het Terracottaleger. Laat hotel of officiële aanbieder de entree en identiteitscontrole voorbereiden.",
      pm: "Lunch en terug voor het dutje. Een bezoek aan stadsmuur of Moslimwijk is een bonus, geen verplichting.",
      eve: "Korte wandeling en vroeg eten.",
      baby: "Ruime hallen maar drukte en loopafstanden: draagzak én buggy naar behoefte.",
      backup: "Inkorten tot de belangrijkste hallen en daarna terug.",
      reserve:
        "Museumticket op naam; boekingsvenster en chauffeur uiterlijk een week vooraf opnieuw controleren.",
      cost: "Tickets + privéauto/gids €100–180 voor het gezin als budget.",
    },
    {
      d: 13,
      city: "chengdu",
      kind: "trein",
      title: "Door de Qinling naar Chengdu.",
      sub: "Xi’an North · Chengdu East",
      am: "Rustig ontbijten, uitchecken en naar Xi’an North.",
      pm: "HSR circa 3u–4u30, transfer naar het appartement. Koffers uitpakken: hier blijven jullie drie nachten.",
      eve: "Een eenvoudige maaltijd. Plan de vroege Panda Base-dag voor morgen.",
      baby: "Dit is een fijn moment voor een was en het aanvullen van luiers/snacks.",
      backup: "Het theehuis kan wachten tot de rustdag.",
      reserve:
        "Treintickets vanaf 26 maart; Panda Base-ticket en vervoer bevestigen.",
      cost: "Trein €30–45 per volwassene.",
    },
    {
      d: 14,
      city: "chengdu",
      kind: "natuur",
      title: "Een ochtend met panda’s.",
      sub: "Chengdu Panda Base",
      am: "Kies het vroegste passende toegangslot en laat de actuele openingstijd controleren. Bezoek een paar verblijven op het koelste moment van de dag.",
      pm: "Lunch en terug naar het appartement. Geen tweede grote attractie.",
      eve: "Eventueel een korte buurtwandeling of simpel diner.",
      baby: "Groot terrein, hellingen en soms veel mensen. Neem de buggy en draagzak mee; houd de route kort.",
      backup: "Bij drukte een beperkt deel bezoeken en op tijd terug.",
      reserve:
        "Panda Base-tijdslot vooraf boeken; exacte 2027-verkoopregels navragen.",
      cost: "Activiteiten en vervoer €35–70 voor het gezin als budget.",
    },
    {
      d: 15,
      city: "chengdu",
      kind: "keuze",
      title: "Leshan. Of gewoon even niets.",
      sub: "Een bonusdag voor het gezin",
      am: "Basisplan: uitslapen, was, ontbijt en People’s Park. Optioneel Leshan alleen als jullie alle drie goed uitgerust zijn.",
      pm: "Voor Leshan: HSR plus lokale transfers vooraf uitwerken; bootzicht kan trappen beperken, maar vaart, leeftijdsregels en weer eerst checken.",
      eve: "Thee, eten en inpakken voor de korte Chongqing-stop.",
      baby: "Een volledige rustdag is hier een uitstekende keuze.",
      backup:
        "Leshan vervalt bij regen of weinig energie. Geen vervangende volle excursie.",
      reserve:
        "Leshan-trein vanaf 28 maart als jullie kiezen; bootvoorwaarden en kinderzitje laten bevestigen.",
      cost: "Rustdag €10–25 aan uitjes; Leshan €80–160 voor het gezin als budget.",
    },
    {
      d: 16,
      city: "chongqing",
      kind: "trein",
      title: "Eén nacht in de neonstad.",
      sub: "Chengdu · Chongqing · Hongya Dong",
      am: "Uitchecken, korte HSR naar Chongqing. Exact aankomststation naar de chauffeur sturen.",
      pm: "Inchecken, lunch en een goede pauze. Niets vastleggen vóór het dutje.",
      eve: "Hongya Dong vanaf een rustig uitzichtpunt bij zonsondergang. Eten en op tijd terug voor de volgende reisdag.",
      baby: "De hoogteverschillen en trappen zijn groot. Draagzak handiger in de drukte; houd de avond kort.",
      backup:
        "Bij regen of vermoeidheid genieten van het rivierzicht in het hotel.",
      reserve:
        "Trein vanaf 29 maart. Beide transfers en vertrekstation voor morgen vastleggen.",
      cost: "Trein €12–30 per volwassene; uitzicht buiten gratis.",
    },
    {
      d: 17,
      city: "zhangjiajie",
      kind: "trein",
      title: "Naar de voet van de Avatarbergen.",
      sub: "Chongqing · Zhangjiajie West · Wulingyuan",
      am: "Hoteltransfer naar het op het ticket genoemde station. HSR naar Zhangjiajie West.",
      pm: "Vooraf geregelde privétransfer naar Wulingyuan, circa 45–75 minuten. Inchecken voor vier nachten.",
      eve: "Rustig eten. Met hotel de weersverwachting en volgorde van de komende bergdagen afstemmen.",
      baby: "Vandaag geen parkbezoek. Draagzak, regenjas en warme laag klaarleggen.",
      backup:
        "Het volledige programma D18–D20 mag op het weer worden aangepast.",
      reserve:
        "Trein vanaf 30 maart; transfer en tickets voor de gekozen parkroute.",
      cost: "Trein €25–45 per volwassene; transfer €25–45 per auto als budget.",
    },
    {
      d: 18,
      city: "zhangjiajie",
      kind: "natuur",
      title: "Tussen stenen torens & wolken.",
      sub: "Yuanjiajie · Bailong Elevator",
      am: "Via de oostelijke ingang en parkshuttle naar de Bailong-lift. Met een vroege start wachtrijen proberen te beperken.",
      pm: "Korte route langs Yuanjiajie-uitzichtpunten. Lunchpauze en tijdig via de gekozen route terug.",
      eve: "Eten in Wulingyuan. Weer en energie voor morgen bekijken.",
      baby: "Draagzak essentieel; liften en shuttles voorkomen niet alle trappen. Geen volledige wandelroute afdwingen.",
      backup:
        "Bij dichte mist deze dag ruilen met een lager gelegen wandeling of rust.",
      reserve:
        "Meerdaags parkentree en lift/shuttle volgens actueel ticketpakket vooraf laten controleren.",
      cost: "Totale Zhangjiajie-activiteitenpot voor D18–D20: €180–280 voor twee; geen dagprijs.",
    },
    {
      d: 19,
      city: "zhangjiajie",
      kind: "natuur",
      title: "Bergpanorama’s & een groene beek.",
      sub: "Tianzi Mountain · Golden Whip Stream",
      am: "Tianzi Mountain met kabelbaan als er goed zicht is. Kies een paar uitzichtpunten.",
      pm: "Golden Whip Stream: alleen een kort stuk van de beekroute. Een volledige combinatie kan lang worden; inkorten of één onderdeel laten vallen mag.",
      eve: "Vroege maaltijd en rust.",
      baby: "Draagzak voor de berg; buggy alleen op geschikte vlakke stukken. Houd ruimte voor regen en omkeren.",
      backup: "Bij mist alleen de beek, bij zware regen een hotelmiddag.",
      reserve:
        "Kabelbaan en parktoegang controleren; niet alle extra ritten zitten in het basiskaartje.",
      cost: "In de gezamenlijke Zhangjiajie-pot bij D18 opgenomen.",
    },
    {
      d: 20,
      city: "zhangjiajie",
      kind: "keuze",
      title: "De mooiste dag bepaalt de route.",
      sub: "Tianmen óf Grand Canyon óf weerbuffer",
      am: "Tianmen bij helder weer en energie: privétransfer naar Zhangjiajie-stad, een apart tijdslot en een route met zo weinig mogelijk trappen.",
      pm: "Alternatief Grand Canyon/glazen brug: vooraf kinderregels, draagzakbeleid en route laten bevestigen. Dit is niet dezelfde locatie als het nationale park.",
      eve: "Rustig inpakken voor morgen. Een ongebruikte bergdag kan vandaag worden ingehaald.",
      baby: "Een volledige rustdag blijft mogelijk. Geen glazen route kiezen zonder bevestigde toelating en passende omstandigheden.",
      backup:
        "D18/D19 inhalen als daar het weer tegenzat; anders hotel, dorp en rust.",
      reserve:
        "Tianmen is een apart ticket met tijdslot en routekeuze. Boek pas na weercheck waar annuleerbaar.",
      cost: "In de gezamenlijke Zhangjiajie-pot; privétransfer naar Tianmen eventueel extra.",
    },
    {
      d: 21,
      city: "yangshuo",
      kind: "trein",
      title: "Een lange treindag. Een zachte landing.",
      sub: "Zhangjiajie · Guilin · Yangshuo",
      am: "Vroege privétransfer naar Zhangjiajie West. Genoeg drinken, eten, luiers en reservekleding voor een volledige reisdag.",
      pm: "Reken op 6u–8u30 trein, mogelijk via Changsha South. Bij overstap 60–90 minuten plannen; alleen het definitieve 2027-schema bepaalt de verbinding.",
      eve: "Chauffeur bij het exacte Guilin-station. Naar het gekozen hotel in Yangshuo, eten en slapen. Inclusief auto’s kan dit een dag van 9–12 uur zijn.",
      baby: "Een eigen treinstoel overwegen en de zitplaatsen samen laten boeken. Geen sightseeing bij aankomst.",
      backup: "Bij late aankomst vooraf maaltijd en late check-in regelen.",
      reserve:
        "Tickets vanaf 3 april, eventuele twee ritten apart bewaken. Hoteltransfer en kinderzitje vooraf.",
      cost: "Trein €45–75 per volwassene; lange aankomsttransfer €55–90 per auto als budget.",
    },
    {
      d: 22,
      city: "yangshuo",
      kind: "rust",
      title: "Vandaag volgt de rivier het tempo.",
      sub: "Yulong River · wandelen & ontspannen",
      am: "Rustig ontbijt met rivierzicht. Korte wandeling langs de Yulong en de velden.",
      pm: "Dutje in het hotel, daarna een terras of kleine wandeling. Geen bamboevlot met Amélie in het basisplan.",
      eve: "Eten bij de rivier en vroeg terug.",
      baby: "Vlotaanbieders hanteren onder meer minimumlengtes; een baby past hier niet in het standaardaanbod. Geniet als gezin vanaf de oever.",
      backup: "Bij regen: hotel, boekje, koffie en kijken naar de bergen.",
      reserve:
        "Niets verplicht. Een volwassene kan eventueel alleen varen terwijl de ander bij Amélie blijft, na controle van de voorwaarden.",
      cost: "Uitjes €0–20 voor het gezin; eten apart.",
    },
    {
      d: 23,
      city: "yangshuo",
      kind: "natuur",
      title: "Het landschap van het twintig-yuanbiljet.",
      sub: "Xingping · Li River",
      am: "Privétransfer naar Xingping. Wandel door het oude dorp en naar een bereikbaar rivieruitzicht.",
      pm: "Lunch en terug voor rust. Optioneel een grotere passagiersboot, alleen als babytoelating en passend reddingsvest bevestigd zijn; geen baby op een klein vlot.",
      eve: "Diner in het hotel of dicht in de buurt.",
      baby: "Basisprogramma vanaf de wal. Geen steile Xianggong-bergwandeling als vaste afspraak.",
      backup: "Bij regen korter naar Xingping, of deze dag ruilen met D24.",
      reserve:
        "Transfer met kinderzitje; eventuele bootkeuze vooraf laten controleren.",
      cost: "Privéauto + uitjes €60–110 voor het gezin als budget.",
    },
    {
      d: 24,
      city: "yangshuo",
      kind: "rust",
      title: "Een hele dag zonder moeten.",
      sub: "Volledige buffer- & familiedag",
      am: "Lang ontbijten. Geen wekker, geen gereserveerde excursie.",
      pm: "Was, spelen, dutje en een kleine wandeling als het droog is.",
      eve: "Laatste avond aan de Yulong. Transfer naar Ping’an en bagageregeling bevestigen.",
      baby: "Deze dag is bewust leeg: herstellen is onderdeel van de reis.",
      backup:
        "Xingping alleen hiernaartoe schuiven als D23 door het weer verviel en iedereen zin heeft.",
      reserve: "Chauffeur voor morgen en Longji–Guilin West op D27 bevestigen.",
      cost: "Uitjes €0–20; eten apart.",
    },
    {
      d: 25,
      city: "longji",
      kind: "transfer",
      title: "Van rivierdal naar rijstterrassen.",
      sub: "Yangshuo · Longji · Ping’an",
      am: "Privétransfer naar Ping’an, reken circa 3u–4u vanaf Yangshuo plus stop en het laatste looptraject.",
      pm: "Bij de parking over op licht bagagevervoer/portier. Inchecken, eten en een korte wandeling bij het dorp.",
      eve: "Diner in het gastenhuis en een rustige avond.",
      baby: "Draagzak essentieel. De buggy helpt op de dorpstrappen weinig; grote bagage vooraf organiseren.",
      backup: "Bij veel regen direct naar het hotel en geen uitzichtwandeling.",
      reserve:
        "Transfer met kinderzitje, portier, exacte trapafstand en bagageopslag schriftelijk regelen.",
      cost: "Privéauto €90–150 per auto; entree en portier €30–55 voor het gezin als budget.",
    },
    {
      d: 26,
      city: "longji",
      kind: "natuur",
      title: "Wakker boven de velden.",
      sub: "Longji-rijstterrassen · korte dorpswandeling",
      am: "Korte wandeling naar een bereikbaar uitzichtpunt. Begin rustig en vraag het hotel welke paden droog en geschikt zijn.",
      pm: "Lunch en dutje. Later nog een klein rondje in Ping’an of een terras.",
      eve: "Laatste avond op mainland China. Chauffeur en treintijden nogmaals bevestigen.",
      baby: "Trappen, hoogteverschillen en natte stenen: draagzak en schoenen met grip. Geen grote trekking.",
      backup:
        "Bij mist genieten van dorp en gastenhuis. April garandeert geen ondergelopen spiegelterrassen; irrigatie verschilt per gebied en jaar.",
      reserve:
        "Niets extra verplicht. Voor morgen voldoende weg- en stationsmarge plannen.",
      cost: "Entree in D25-pot opgenomen; lokaal extra’s €0–20.",
    },
    {
      d: 27,
      city: "hongkong",
      kind: "trein",
      title: "Rechtstreeks naar Hongkong.",
      sub: "Ping’an · Guilin West · West Kowloon",
      am: "Vroege privétransfer vanaf Ping’an naar Guilin West, circa 2u–3u afhankelijk van ophalen en weg. Plan ook portier en minimaal 60–90 minuten op het station.",
      pm: "Voorkeur: directe HSR naar Hong Kong West Kowloon, circa 3u10–3u20 als routebasis. Geen verplichte overstap in Guangzhou. Paspoorten bij de hand.",
      eve: "Grensformaliteiten bij aankomst, transfer naar hotel in Kowloon en rustig eten. Drie nachten Hongkong.",
      baby: "Dit is een volle transferdag. Geen avondtour vastleggen.",
      backup:
        "Als geen directe geschikte dienst beschikbaar is: ruime overstap via Guangzhou South of Shenzhen North uitwerken.",
      reserve:
        "Tickets vanaf 9 april; 2027-dienst bevestigen en alle reizigers correct registreren.",
      cost: "Trein €40–65 per volwassene; auto Longji–Guilin West €70–110 als budget.",
    },
    {
      d: 28,
      city: "hongkong",
      kind: "cultuur",
      title: "Van Star Ferry tot de Peak.",
      sub: "Hong Kong Island · Central · Victoria Peak",
      am: "Star Ferry naar Hong Kong Island en een korte wandeling door Central.",
      pm: "Hotelpauze of rustige lunch. Victoria Peak bij goed zicht; kies taxi/Peak Tram op basis van wachtrij en energie.",
      eve: "Diner en, als het past, even naar de verlichte haven.",
      baby: "Buggy voor promenade en veerboot; Central heeft hellingen en trappen. Houd de Peak als flexibel onderdeel.",
      backup:
        "Bij laaghangende wolken de Peak laten vallen en aan de haven blijven.",
      reserve:
        "Peak-optie pas kiezen na weercheck. Ferryregelingen en tarieven voor 2027 controleren.",
      cost: "Activiteiten en vervoer €35–80 voor het gezin als budget.",
    },
    {
      d: 29,
      city: "hongkong",
      kind: "rust",
      title: "Kowloon op z’n gemak.",
      sub: "Victoria Harbour · een rustige dag",
      am: "Rustig ontbijt en promenade bij Tsim Sha Tsui, met zicht op de skyline.",
      pm: "Dutje, koffie en een klein rondje Kowloon. Geen Disneyland of grote excursie toevoegen.",
      eve: "Laatste volledige hotelavond. Een fijn diner is genoeg.",
      baby: "Goed moment om het ritme te bewaren vóór de nachtvlucht.",
      backup: "Bij regen een winkelcentrum, museum naar keuze of hotelmiddag.",
      reserve:
        "Bagageopslag en eventuele late checkout voor morgen bevestigen.",
      cost: "Uitjes €0–25 voor het gezin; eten apart.",
    },
    {
      d: 30,
      city: "hongkong",
      kind: "vlucht",
      title: "Nog één dag. Dan vliegen we naar huis.",
      sub: "Hotelcheckout · HKG 23:55 · Frankfurt",
      am: "Ontbijt en uitchecken volgens het hotelbeleid. Bagage bij het hotel opslaan; essentials voor Amélie in de dagtas.",
      pm: "Een rustige wandeling of een vooraf geboekte dagkamer/late checkout. Daar kan Amélie nog slapen en kunnen jullie opfrissen.",
      eve: "Bagage ophalen. Vertrek met ruime marge naar HKG; mik rond 20:30–20:55 op de luchthaven. Vlucht om 23:55 naar Frankfurt met Cathay Pacific.",
      baby: "Dagkamer of late checkout is een waardevolle extra voor de lange dag. Kinderzitje voor de vlucht en eigen stoel opnieuw bevestigen.",
      backup:
        "Bij regen/vermoeidheid hotel of dagkamer. Geen attractie met vaste eindtijd.",
      reserve:
        "HKG-transfer met kinderzitje of Airport Express-route uitwerken. Bagageopslag/dagkamer vooraf bevestigen.",
      cost: "Airporttransfer €35–70 als budget; late checkout/dagkamer apart.",
      sleep: "In het vliegtuig",
    },
    {
      d: 31,
      city: "reis",
      kind: "vlucht",
      title: "Thuis op Koningsdag.",
      sub: "Frankfurt · Amsterdam · aankomst 10:35",
      am: "Overstap in Frankfurt op Lufthansa. Exacte aansluiting en gate volgens het ticket. Aankomst AMS 10:35 lokale tijd.",
      pm: "Naar huis, uitpakken kan later. Geen afspraken plannen.",
      eve: "Rustig in het eigen ritme komen.",
      baby: "Ook op FRA–AMS moet het eigen zitje door de uitvoerende maatschappij zijn geaccepteerd.",
      backup:
        "Bij aansluitingsproblemen de luchtvaartmaatschappij laten omboeken; ruimte houden voor herstel.",
      reserve: "Ophalen vanaf Schiphol of taxi met passend kinderzitje.",
      cost: "Vervoer naar huis apart van het landbudget.",
      sleep: "Thuis",
    },
  ],
  videos: [
    {
      id: "-uJSab801Z4",
      title: "China vanuit de trein",
      area: "Shanghai · Beijing",
      credit: "Simon Andersen · video uit de spoor27-route",
      note: "First Class-video voor sfeer en treinervaring; ons budget rekent met 2e klas en een rit via Hangzhou.",
    },
    {
      id: "siFRKIJHbWg",
      title: "Tussen de Avatarbergen",
      area: "Zhangjiajie · Wulingyuan",
      credit: "FOLLOW ME · Hunan Province",
      note: "Een voorproefje van de bergen; de dagindeling passen jullie aan op het weer.",
    },
    {
      id: "86y_JC-jirM",
      title: "Het mooiste groen van China",
      area: "Yangshuo · Li River",
      credit: "Asia Odyssey Travel · Guilin",
      note: "Landschapsinspiratie. De vlotactiviteiten in de video zijn geen babyprogramma.",
    },
  ],
};
