/* Definitieve reisbasis van Ruben en Martine; spoor27 blijft het oorspronkelijke vergelijkingsscenario. */
window.CHINA2027 = {
  checked: "2026-09-30",
  flightTotal: 1671.68,
  stays: [
    {
      id: "shanghai",
      budget: {
        hotel: "Campanile Shanghai Bund",
        area: "Huangpu / Bund en Yu Garden",
        room: "King / Twin · babybed en kameroppervlak navragen",
        low: 50,
        high: 75,
        url: "https://shanghai-bund.campanile.com/en-us/",
        why: "Een compactere stadsbasis bij de Bund, met een lager kamerbudget.",
        check:
          "Vroege check-in, babybed, rookvrije kamer en totale prijs voor twee volwassenen + baby bevestigen.",
      },
      name: "Shanghai",
      cn: "上海",
      start: 2,
      nights: 3,
      lat: 31.2304,
      lng: 121.4737,
      hotel: "Pullman Shanghai Central",
      room: "Superior King · 48 m²",
      area: "Huangpu / voormalige Franse Concessie",
      low: 100,
      high: 155,
      url: "https://pullman.accor.com/en/hotels/shanghai/7298/rooms.html",
      why: "Een ruime eerste basis om te landen, met plek voor een babybed en de buggy.",
      check:
        "Babybed, rustige rookvrije kamer en vroege toegang na aankomst om 06:30 schriftelijk aanvragen. Gegarandeerde vroege check-in kan een extra nacht kosten.",
      highlight: "De Bund, tuinen en een eerste kom noedels.",
      image: "shanghai",
    },
    {
      id: "hangzhou",
      budget: {
        hotel: "Holiday Inn Express Hangzhou Westlake East",
        area: "Westlake Avenue / bij Hangzhou Railway Station",
        room: "Standard King · babybed op aanvraag",
        low: 45,
        high: 70,
        url: "https://www.ihg.com/holidayinnexpress/hotels/us/en/hangzhou/hghwe/hoteldetail",
        why: "Praktische ketenbasis; voor West Lake een korte rit plannen in plaats van het Kerry Centre-budget.",
        check:
          "Niet verwarren met Hangzhou East station. Ontbijt, babybed en eventuele 6% btw controleren.",
      },
      name: "Hangzhou",
      cn: "杭州",
      start: 5,
      nights: 2,
      lat: 30.25,
      lng: 120.149,
      hotel: "Midtown Shangri-La, Hangzhou",
      room: "Deluxe King · kamertype bevestigen",
      area: "Kerry Centre / West Lake",
      low: 130,
      high: 185,
      url: "https://www.shangri-la.com/hangzhou/midtownshangrila/",
      why: "West Lake op loopafstand: fijn voor korte wandelingen en terug naar de kamer tijdens het dutje.",
      check:
        "Babybed en rookvrije kamer aanvragen. Ontbijt, totale kamerprijs en annuleringsvoorwaarden controleren.",
      highlight: "Van skyline naar theegroene heuvels.",
    },
    {
      id: "beijing",
      budget: {
        hotel: "Citytel Inn",
        area: "Nanheyan / Dongcheng, nabij Wangfujing",
        room: "Double · ruimte voor babybed nog bevestigen",
        low: 55,
        high: 85,
        url: "https://www.trip.com/hotels/beijing-hotel-detail-436626/citytel-inn/",
        why: "Centrale eenvoud: minder kamercomfort, dezelfde vier nachten voor de belangrijkste uitstappen.",
        check:
          "Babybed en kameroppervlak schriftelijk bevestigen; Qingming kan de raming verhogen.",
      },
      name: "Beijing",
      cn: "北京",
      start: 7,
      nights: 4,
      lat: 39.916,
      lng: 116.412,
      hotel: "Park Plaza Beijing Wangfujing",
      room: "Superior / Deluxe · ruimte voor babybed navragen",
      area: "Wangfujing / Dongcheng",
      low: 100,
      high: 165,
      url: "https://www.radissonhotels.com/en-us/hotels/park-plaza-beijing-wangfujing",
      why: "Centrale uitvalsbasis voor de keizerstad, zonder iedere dag van hotel te wisselen.",
      check:
        "Babybed, rustige kamer en privétransfer naar Mutianyu met passend kinderzitje bevestigen. Qingming kan prijzen en drukte verhogen.",
      highlight: "Keizerlijke daken. Een muur tot aan de horizon.",
    },
    {
      id: "xian",
      budget: {
        hotel: "Campanile Xi’an Bell Tower Huimin Street",
        area: "Binnen de stadsmuur / Bell Tower",
        room: "King / Twin · kamertype bevestigen",
        low: 35,
        high: 55,
        url: "https://www.booking.com/hotel/cn/campanile-xian-bell-tower.html",
        why: "Eenvoudige centrale hotelkeuze bij de torens; het boutiquehotel blijft ernaast beschikbaar.",
        check:
          "Babybed, lift, rookvrije kamer en definitieve gezinsprijs bevestigen.",
      },
      name: "Xi’an",
      cn: "西安",
      start: 11,
      nights: 2,
      lat: 34.253,
      lng: 108.943,
      hotel: "Eastern House Boutique Hotel",
      room: "King / Twin · kamertype controleren",
      area: "Binnen de stadsmuur / Beilin",
      low: 70,
      high: 110,
      url: "https://www.eastern-house.cn/en/",
      why: "Een centrale boutique-basis voor het Terracottaleger en een korte avondwandeling.",
      check:
        "Vraag naar babybed, rustige verdieping en een chauffeur met kinderzitje voor de museumdag.",
      highlight: "Een leger van klei, een stad vol verhalen.",
    },
    {
      id: "chengdu",
      budget: {
        hotel: "Holiday Inn Express Chengdu Tianfu Square",
        area: "Tianfu Square / stadscentrum",
        room: "Standard King · babybed navragen",
        low: 40,
        high: 65,
        url: "https://www.ihg.com/holidayinnexpress/hotels/us/en/chengdu/ctuts/hoteldetail",
        why: "Een gewone hotelkamer als voordeliger alternatief voor het Somerset-appartement.",
        check:
          "Babybed en ontbijt bevestigen; voor wasgoed een wasserette of hotelservice plannen.",
      },
      name: "Chengdu",
      cn: "成都",
      start: 13,
      nights: 3,
      lat: 30.647,
      lng: 104.065,
      hotel: "Somerset Riverview Chengdu",
      room: "Appartement · indeling en wasfaciliteiten navragen",
      area: "Jinjiang-rivier / Wuhou",
      low: 65,
      high: 105,
      url: "https://www.discoverasr.com.cn/somerset-serviced-residence/china/somerset-riverview-chengdu",
      why: "Een appartement is prettig voor een wasmoment, eenvoudige maaltijden en drie ontspannen nachten.",
      check:
        "Vraag naar een aparte slaapruimte, eigen wasmachine, babybed en de rit naar de Panda Base.",
      highlight: "Panda’s in de ochtend. Thee in de middag.",
    },
    {
      id: "chongqing",
      budget: {
        hotel: "Mercure Chongqing Downtown",
        area: "Jiefangbei / Yuzhong",
        room: "Standard King · kamertype bevestigen",
        low: 50,
        high: 80,
        url: "https://all.accor.com/hotel/B330/index.es.shtml",
        why: "Een centrale overnachting voor Hongya Dong zonder de voco-kamerprijs.",
        check:
          "Babybed, beide stationstransfers en rookvrije kamer vooraf bevestigen.",
      },
      name: "Chongqing",
      cn: "重庆",
      start: 16,
      nights: 1,
      lat: 29.563,
      lng: 106.584,
      hotel: "voco Chongqing Chaotianmen",
      room: "Standard / Premium · rivierzicht optioneel",
      area: "Chaotianmen / Yuzhong",
      low: 95,
      high: 155,
      url: "https://www.ihg.com/voco/hotels/gb/en/chongqing/ckgct/hoteldetail",
      why: "De enige korte stop: comfortabel inchecken en ’s avonds even naar de verlichte rivierstad.",
      check:
        "Beide stationstransfers vastleggen, inclusief exact station, kinderzitje en de volgende ochtend vertrektijd.",
      highlight: "Een futuristische stad die ’s avonds aangaat.",
    },
    {
      id: "zhangjiajie",
      budget: {
        hotel: "Maosao Inn",
        area: "Wulingyuan / Wuling Road",
        room: "Double · babybed en toegang navragen",
        low: 35,
        high: 60,
        url: "https://www.trip.com/hotels/zhangjiajie-hotel-detail-3000682/maosao-inn/",
        why: "Kleine accommodatie in Wulingyuan; vier nachten en de weerbuffer blijven behouden.",
        check:
          "Lift/trappen, babybed, verwarming, rookvrije kamer en rit naar de parkingang bevestigen.",
      },
      name: "Wulingyuan",
      cn: "武陵源",
      start: 17,
      nights: 4,
      lat: 29.347,
      lng: 110.551,
      hotel: "Hampton by Hilton Zhangjiajie National Forest Park",
      room: "King · babybed op aanvraag",
      area: "Wulingyuan / oostelijke parkingang",
      low: 80,
      high: 130,
      url: "https://www.hilton.com/en/hotels/dygzjhx-hampton-zhangjiajie-national-forest-park/",
      why: "Volgens Hilton circa 500 meter van de oostelijke ticketingang. Vier nachten geven ruimte om de bergdagen op het weer af te stemmen.",
      check:
        "Niet verwarren met de Hampton bij Tianmen in de stad. Transfer Zhangjiajie West–Wulingyuan en eventuele Tianmen-dag vooraf regelen.",
      highlight: "Vier nachten tussen de Avatarbergen.",
      image: "zhangjiajie",
    },
    {
      id: "yangshuo",
      budget: {
        hotel: "Yangshuo River View Hotel",
        area: "Yangshuo-centrum / Li River",
        room: "Double · rustige kamer navragen",
        low: 40,
        high: 65,
        url: "https://www.booking.com/hotel/cn/yang-shuo-wang-jiang-lou-jiu-dian.de.html",
        why: "Een stadsbasis aan de Li River; voordeliger, maar voor Yulong River een transfer nodig.",
        check:
          "Babybed, lift en stilte in de avond bevestigen. Dit hotel ligt niet aan de Yulong.",
      },
      name: "Yangshuo",
      cn: "阳朔",
      start: 21,
      nights: 4,
      lat: 24.748,
      lng: 110.45,
      hotel: "Yangshuo Mountain Retreat",
      room: "Riverview / Family · kamertype navragen",
      area: "Yulong River / buiten het centrum",
      low: 80,
      high: 135,
      url: "https://www.yangshuomountainretreat.com/",
      why: "Slapen bij de rivier en het landschap: hier mag het tempo vier nachten omlaag.",
      check:
        "Babybed, trapvrije bereikbaarheid, transfers en eetmogelijkheden vragen. Water dichtbij: Amélie steeds onder toezicht.",
      highlight: "Karstbergen, rivierlicht en nergens haast.",
      image: "yangshuo",
    },
    {
      id: "longji",
      budget: {
        hotel: "Longji Holiday Hotel",
        area: "Ping’an Village / rijstterrassen",
        room: "Double · kamertype bevestigen",
        low: 30,
        high: 50,
        url: "https://www.booking.com/hotel/cn/longji-holiday.en-gb.html",
        why: "Eenvoudiger slapen in hetzelfde bergdorp, met behoud van twee nachten in de terrassen.",
        check:
          "Portier, trappen, babybed, verwarming en vervoer voor bagage vooraf bevestigen.",
      },
      name: "Longji / Ping’an",
      cn: "龙脊 · 平安",
      start: 25,
      nights: 2,
      lat: 25.755,
      lng: 110.133,
      hotel: "Longji One Art Hotel",
      room: "Double / Family · verwarming navragen",
      area: "Ping’an-dorp / rijstterrassen",
      low: 70,
      high: 115,
      url: "https://www.booking.com/hotel/cn/long-ji-the-one.nl.html",
      why: "Twee nachten midden in het terraslandschap, met tijd voor korte wandelingen.",
      check:
        "Trappen naar het hotel: portier, bagagevervoer, laatste looptraject en kinderbed bevestigen. Houd de grote koffer zo mogelijk bij de chauffeur of in opslag.",
      highlight: "Wakker worden boven de rijstterrassen.",
    },
    {
      id: "hongkong",
      budget: {
        hotel: "B P International",
        area: "Tsim Sha Tsui / bij Kowloon Park",
        room: "City Vista · babybed en ruimte navragen",
        low: 90,
        high: 140,
        url: "https://www.bpih.com.hk/accommodation",
        why: "Een praktische Kowloon-basis als alternatief voor de grotere Salon-kamer bij Eaton.",
        check:
          "Babybed, bagageopslag, kamerruimte en totaal inclusief 10% service en 3% hotelbelasting bevestigen.",
      },
      name: "Hongkong",
      cn: "香港",
      start: 27,
      nights: 3,
      lat: 22.307,
      lng: 114.171,
      hotel: "Eaton HK",
      room: "Salon · circa 28 m²",
      area: "Jordan / Kowloon",
      low: 140,
      high: 220,
      url: "https://www.eatonworkshop.com/en-us/hong-kong/",
      why: "Een leuke, praktische Kowloon-basis met eetmogelijkheden en meer ruimte in een Salon-kamer.",
      check:
        "Babybed, bagageopslag op 26 april, dagkamer of late checkout aanvragen. Controleer of 10% servicekosten en 3% accommodation tax in de getoonde prijs zitten.",
      highlight: "Nog één skyline. En dan samen naar huis.",
    },
  ],
  trains: [
    {
      day: 5,
      from: "Shanghai Hongqiao 上海虹桥",
      to: "Hangzhou East 杭州东",
      time: "0u45–1u15",
      low: 8,
      high: 15,
      note: "Zoek op Hongqiao, niet op het centrale Shanghai-station. Na de trein een korte hoteltransfer.",
    },
    {
      day: 7,
      from: "Hangzhou East 杭州东",
      to: "Beijing South 北京南",
      time: "4u45–6u30",
      low: 75,
      high: 110,
      note: "Voorkeur: rechtstreekse ochtendtrein. Extra drukte rond Qingming; boek bij opening.",
    },
    {
      day: 11,
      from: "Beijing West 北京西",
      to: "Xi’an North 西安北",
      time: "4u10–6u",
      low: 60,
      high: 90,
      note: "Let op: vertrek waarschijnlijk vanaf Beijing West, dus een ander station dan bij aankomst.",
    },
    {
      day: 13,
      from: "Xi’an North 西安北",
      to: "Chengdu East 成都东",
      time: "3u–4u30",
      low: 30,
      high: 45,
      note: "Directe HSR als basis; station en vertrektijd op het boekbare schema bevestigen.",
    },
    {
      day: 16,
      from: "Chengdu East 成都东",
      to: "Chongqing · station te bepalen",
      time: "1u–2u",
      low: 12,
      high: 30,
      note: "Chongqing North, West of East kan per trein verschillen. Chauffeur krijgt het exacte station op het ticket.",
    },
    {
      day: 17,
      from: "Chongqing · station te bepalen",
      to: "Zhangjiajie West 张家界西",
      time: "2u–3u30",
      low: 25,
      high: 45,
      note: "Het vertrekstation hangt af van de dienst. Daarna circa 45–75 minuten privétransfer naar Wulingyuan.",
    },
    {
      day: 21,
      from: "Zhangjiajie West 张家界西",
      to: "Guilin · station te bepalen",
      time: "6u–8u30",
      low: 45,
      high: 75,
      note: "Kritische rit: 2026-voorbeeld D3967 07:12–14:13 naar Guilin North; dit vraagt zeer vroeg vertrek uit Wulingyuan. In 2027 een latere directe dienst zoeken als die rijdt. Overstap bij voorkeur op hetzelfde station; Changsha en Changsha South niet verwarren. Daarna circa 1u30–2u hoteltransfer.",
    },
    {
      day: 27,
      from: "Guilin West 桂林西",
      to: "Hong Kong West Kowloon 香港西九龙",
      time: "circa 3u10–3u20",
      low: 40,
      high: 65,
      note: "Voorkeur: rechtstreekse HSR. De route bestaat in het huidige netwerk; duur en dienst in 2027 bevestigen. Guangzhou alleen als terugvaloptie. Na aankomst grensformaliteiten en hoteltransfer.",
    },
  ],
  days: [
    {
      d: 1,
      city: "reis",
      kind: "vlucht",
      title: "De reis begint.",
      sub: "Amsterdam · Zürich · Shanghai",
      am: "Rond 06:50 op Schiphol als werkmarge. SWISS vertrekt om 09:50 uit AMS; paspoorten, babyspullen en kinderzitje bij de hand.",
      pm: "Overstap in Zürich. Exacte aansluiting, terminal en overstaptijd controleren op de vluchtbevestiging.",
      eve: "Nachtvlucht naar Shanghai. Eigen stoel voor Amélie met een voor alle uitvoerende maatschappijen bevestigd vliegtuiggeschikt zitje.",
      baby: "Reserveer de eigen stoel vóór het kiezen van zitplaatsen. Het SWISS-bassinet is bij bijna 11 maanden geen optie.",
      backup:
        "Een ruime overstap en reservekleding voor alle drie in de handbagage.",
      reserve:
        "Eigen stoel, zitje en zitplaatsen op beide SWISS-segmenten schriftelijk bevestigen.",
      cost: "Vluchten: werkelijk betaalde gezinsprijs invullen bij Budget.",
      sleep: "In het vliegtuig",
    },
    {
      d: 2,
      city: "shanghai",
      kind: "rust",
      title: "Hallo Shanghai. Vandaag alleen landen.",
      sub: "Aankomst PVG 06:30 · rustdag",
      am: "Landen om 06:30 lokale tijd. Immigratie, bagage en vooraf geregelde transfer naar het hotel; geen sightseeing-afspraak.",
      pm: "Rust, douchen en een eerste dutje. Vroege check-in aanvragen; boek desgewenst een extra nacht als toegang tot de kamer gegarandeerd moet zijn.",
      eve: "Een korte wandeling in de buurt, makkelijk eten en vroeg terug.",
      baby: "De klok staat zes uur later dan in Nederland. Houd het ritme soepel en plan geen lange wandeling.",
      backup: "Alleen het hotel is vandaag al een goed programma.",
      reserve:
        "PVG-transfer met passend kinderzitje en vroege kamer gereedmaken.",
      cost: "Transfer €50–85 per auto als budget; vroege check-in apart.",
    },
    {
      d: 3,
      city: "shanghai",
      kind: "cultuur",
      title: "Yu Garden & de Bund.",
      sub: "Oud Shanghai, nieuwe skyline",
      am: "Rond 09:00 naar Yu Garden. Bezoek de tuin op rustig tempo; neem een draagzak mee voor smalle paadjes en trappen.",
      pm: "Lunch en dutje in het hotel. Daarna een korte wandeling over de Bund.",
      eve: "Als er energie is: skyline bij het blauwe uur. Anders vroeg eten dichtbij het hotel.",
      baby: "Vandaag twee korte blokken, met een echte pauze ertussen. De buggy is fijn op de Bund.",
      backup:
        "Bij regen: een overdekte lunch en een korte Bund-wandeling zodra het droog wordt.",
      reserve:
        "Yu Garden openingstijden en eventueel ticket vooraf controleren.",
      cost: "Activiteitenpot €15–30 voor twee volwassenen, exclusief eten en lokaal vervoer.",
    },
    {
      d: 4,
      city: "shanghai",
      kind: "keuze",
      title: "Shanghai van dichtbij. Of boven de skyline.",
      sub: "Franse Concessie · Tower óf Zhujiajiao",
      am: "Ons rustige voorkeursplan: een kort rondje Wukang Road / Anfu Road in de voormalige Franse Concessie, met koffie en tijd om terug te keren. Kies bij helder zicht in plaats daarvan Shanghai Tower, of maak van Zhujiajiao de enige hoofdexcursie.",
      pm: "Lunch en hotelpauze. De stadswandeling kan in een blok van 60–90 minuten; stapel waterdorp, Tower en stadswijken niet op dezelfde dag.",
      eve: "Laatste avond Shanghai: eten in de buurt en rustig inpakken voor de trein.",
      baby: "De stadswandeling houdt de hotelpauze dichtbij. Voor bruggen in Zhujiajiao de draagzak meenemen.",
      backup:
        "Geen helder uitzicht of weinig energie? Wukang / Anfu, een café en terug naar het hotel.",
      reserve:
        "Wandelen vraagt geen tijdslot. Tower pas na weercheck; Zhujiajiao met transfer en kinderzitje.",
      cost: "Wandelen gratis, koffie en eten uit de eetpot. Tower circa €45–65 voor twee; waterdorp met privéauto circa €100–160 als budget.",
    },
    {
      d: 5,
      city: "hangzhou",
      kind: "trein",
      title: "Per spoor naar het West Lake.",
      sub: "Shanghai Hongqiao · Hangzhou East",
      am: "Uitchecken en naar Shanghai Hongqiao. Mik op 60–90 minuten stationsmarge met Amélie.",
      pm: "HSR naar Hangzhou East, hoteltransfer en inchecken. Laat de middag open.",
      eve: "Als het uitkomt: even langs het West Lake wandelen en vroeg eten.",
      baby: "Houd fles, luiers, doekjes en een kleine snacktas buiten de grote koffer.",
      backup:
        "Regen? Geen meerwandeling nodig: hotel en restaurant zijn genoeg.",
      reserve:
        "Treinticket vanaf 18 maart; exacte vrijgavetijd van het vertrekstation controleren.",
      cost: "Trein €8–15 per volwassene; transfer en hotel apart.",
    },
    {
      d: 6,
      city: "hangzhou",
      kind: "cultuur",
      title: "Thee, tempels & een meer.",
      sub: "West Lake · Longjing · Lingyin",
      am: "Rustige wandeling aan West Lake. Kies daarna Longjing-theevelden óf Lingyin als hoofdbezoek.",
      pm: "Na lunch een hotelpauze. Het tweede bezoek alleen toevoegen als iedereen energie heeft; niet alle drie locaties achter elkaar afwerken.",
      eve: "Diner rond het meer of dicht bij het hotel.",
      baby: "Theevelden en tempels hebben trappen: draagzak mee. Geef het dutje de beste plek in de dag.",
      backup: "Bij veel regen: theehuis, korte oeverwandeling en rust.",
      reserve:
        "Voor Lingyin de officiële actuele entree- en reserveringsregels laten controleren door het hotel.",
      cost: "Activiteiten €20–45 voor twee; privévervoer optioneel.",
    },
    {
      d: 7,
      city: "beijing",
      kind: "trein",
      title: "Op naar de keizerstad.",
      sub: "Hangzhou East · Beijing South",
      am: "Ontbijt, uitchecken en vroege hoteltransfer naar Hangzhou East. Een rechtstreekse HSR heeft de voorkeur.",
      pm: "Treinreis circa 4u45–6u30. Lunch, dutje en korte loopmomenten in het rijtuig.",
      eve: "Aankomst Beijing South, transfer en inchecken. Eten in de buurt; geen hutongtour vastzetten.",
      baby: "Stoelen naast elkaar aanvragen. Een eigen stoel voor Amélie kan via een betaald kinderticket; voorwaarden vooraf navragen.",
      backup: "Als aankomst later wordt: alleen naar het hotel.",
      reserve:
        "Trein vanaf 20 maart; Qingming maakt deze periode extra boekingsgevoelig.",
      cost: "Trein €75–110 per volwassene.",
    },
    {
      d: 8,
      city: "beijing",
      kind: "cultuur",
      title: "Door de poorten van de Verboden Stad.",
      sub: "Forbidden City · Jingshan",
      am: "Bezoek de Verboden Stad met een bevestigd tijdslot en dezelfde originele paspoorten als bij de reservering. Start via de zuidelijke toegang volgens ticketinstructies.",
      pm: "Eenvoudige lunch. Jingshan alleen als er energie is: voor het uitzicht moet je omhoog; anders terug naar het hotel.",
      eve: "Vroeg Pekingeend eten als jullie daar zin in hebben; kies een tafel bij het hotel in plaats van een late avondtour. Mutianyu-transfer voor morgen bevestigen.",
      baby: "Maak een verkorte route door de paleiscomplexen. Niet elk paviljoen hoeft vandaag.",
      backup:
        "Geen ticket? Vandaag park/hutongs, en alleen naar een andere open dag schuiven als daar tickets beschikbaar zijn.",
      reserve:
        "Forbidden City: 28 maart om 20:00 Beijing / 14:00 Nederland. Jullie zijn dan op reis: regel vooraf toegang en hulp bij boeken. Tiananmen Square is een aparte optionele stop met eigen reserveringsregels; laat de route naar de paleisingang bevestigen.",
      cost: "Activiteitenpot €20–35 voor twee, inclusief eventuele extra paleiszalen.",
    },
    {
      d: 9,
      city: "beijing",
      kind: "natuur",
      title: "Een muur tot aan de horizon.",
      sub: "Mutianyu Great Wall · Qingming",
      am: "Vroege privétransfer naar Mutianyu, circa 1u30–2u per richting afhankelijk van verkeer. Kies de gesloten kabelbaan en een kort traject op de muur.",
      pm: "Lunch en terug naar Beijing. Reken op trappen, hellingen en wachtrijen; stop ruim vóór het op is.",
      eve: "Een rustige avond in het hotel.",
      baby: "Draagzak essentieel. Geen buggy op de muur en geen rodelbaan met Amélie.",
      backup:
        "Bij slecht weer of extreme drukte ruilen met D10, als chauffeur en tickets dat toelaten. De Verboden Stad alleen verplaatsen met een nieuw bevestigd ticket.",
      reserve:
        "Kabelbaan/entree en chauffeur vooraf regelen. Qingming op 5 april: definitief vakantieblok 2027 controleren. Als 6 april duidelijk rustiger is, Mutianyu en D10 omwisselen.",
      cost: "Privéauto + entree/kabelbaan €140–220 voor het gezin als budget.",
    },
    {
      d: 10,
      city: "beijing",
      kind: "cultuur",
      title: "De tempel. Daarna het dagelijkse Beijing.",
      sub: "Temple of Heaven · Shichahai / hutongs",
      am: "Temple of Heaven: park en hoofdcomplex op rustig tempo. Dit is het enige grote bezoek van vandaag.",
      pm: "Eerst een echte hotelpauze. Daarna optioneel 45–60 minuten langs Shichahai en een rustige hutong, bijvoorbeeld rond Yandai Xiejie. Summer Palace blijft een alternatief voor deze dag: kies het dan als hoofdbezoek in plaats van Temple of Heaven, niet als extra complex.",
      eve: "Eten, spullen bij elkaar en Beijing West voor morgen controleren. Een korte buurtwandeling mag ook genoeg zijn.",
      baby: "Buggy in park en langs het meer; draagzak bij trappen. Het hutongrondje mag direct worden afgebroken als het dutje niet lukte.",
      backup:
        "Bij regen of vermoeidheid vervalt de hutongwandeling. Indien nodig ruilen met de Mutianyu-dag; tickets en chauffeur eerst bevestigen.",
      reserve:
        "Opening/entree voor het gekozen hoofdbezoek controleren. Hutongs vrij verkennen; geen verplichte riksjarit.",
      cost: "Entreepot circa €15–35 voor twee als raming; hutongwandeling gratis, vervoer en eten apart.",
    },
    {
      d: 11,
      city: "xian",
      kind: "trein",
      title: "Van keizerstad naar zijderoute.",
      sub: "Beijing West · Xi’an North",
      am: "Uitchecken en naar Beijing West. Controleer het station: niet automatisch terug naar Beijing South.",
      pm: "HSR naar Xi’an North, circa 4u10–6u. Privétransfer naar het hotel binnen de stadsmuur.",
      eve: "Na inchecken alleen als er energie is: een kort rondje bij Bell / Drum Tower en de Moslimwijk voor eten. Anders bij het hotel blijven.",
      baby: "Geen vaste stadsmuurwandeling op een treindag. De Moslimwijk kan druk zijn: kies een kort stuk en keer makkelijk om.",
      backup: "Bij vertraging direct hotel en roomservice.",
      reserve: "Treintickets vanaf 24 maart; aankomsttransfer vooraf.",
      cost: "Trein €60–90 per volwassene.",
    },
    {
      d: 12,
      city: "xian",
      kind: "cultuur",
      title: "Oog in oog met het Terracottaleger.",
      sub: "Een halve dag vol verwondering",
      am: "Vroeg met chauffeur naar het Terracottaleger. Laat hotel of officiële aanbieder de entree en identiteitscontrole voorbereiden.",
      pm: "Lunch en terug voor het dutje. Kies daarna hooguit één extra: een kort bezoek aan de stadsmuur bij Yongningmen óf eten in de Moslimwijk. De muur is een bonus, geen volledige wandeling of fietstocht.",
      eve: "Dumplings of biangbiang-noedels en vroeg terug. Moslimwijk alleen als jullie dat korte rondje nog niet hebben gedaan.",
      baby: "Ruime hallen maar drukte en loopafstanden: draagzak én buggy naar behoefte.",
      backup: "Inkorten tot de belangrijkste hallen en daarna terug.",
      reserve:
        "Museumticket op naam; verkoopvenster en chauffeur uiterlijk een week vooraf controleren. Voor een extra muurbezoek entree, opening en trappen bij Yongningmen navragen.",
      cost: "Tickets + privéauto/gids €100–180 voor het gezin als budget.",
    },
    {
      d: 13,
      city: "chengdu",
      kind: "trein",
      title: "Door de Qinling naar Chengdu.",
      sub: "Xi’an North · Chengdu East",
      am: "Rustig ontbijten, uitchecken en naar Xi’an North.",
      pm: "HSR circa 3u–4u30, transfer naar het gekozen hotel of appartement. Koffers uitpakken: hier blijven jullie drie nachten.",
      eve: "Een eenvoudige maaltijd. Plan de vroege Panda Base-dag voor morgen.",
      baby: "Dit is een fijn moment voor een was en het aanvullen van luiers/snacks.",
      backup: "Het theehuis kan wachten tot de rustdag.",
      reserve:
        "Treintickets vanaf 26 maart; Panda Base-ticket en vervoer bevestigen.",
      cost: "Trein €30–45 per volwassene.",
    },
    {
      d: 14,
      city: "chengdu",
      kind: "natuur",
      title: "Een ochtend met panda’s.",
      sub: "Chengdu Panda Base",
      am: "Kies het vroegste passende toegangslot en laat de actuele openingstijd controleren. Bezoek een paar verblijven op het koelste moment van de dag.",
      pm: "Lunch en terug naar het gekozen hotel of appartement. Geen tweede grote attractie.",
      eve: "Eventueel een korte buurtwandeling of simpel diner.",
      baby: "Groot terrein, hellingen en soms veel mensen. Neem de buggy en draagzak mee; houd de route kort.",
      backup: "Bij drukte een beperkt deel bezoeken en op tijd terug.",
      reserve:
        "Panda Base-tijdslot vooraf boeken; exacte 2027-verkoopregels navragen.",
      cost: "Activiteiten en vervoer €35–70 voor het gezin als budget.",
    },
    {
      d: 15,
      city: "chengdu",
      kind: "keuze",
      title: "Thee tussen de locals. Of Leshan.",
      sub: "People’s Park · Heming-theehuis / Leshan optioneel",
      am: "Voorkeur: rustig ontbijten en People’s Park met thee bij Heming. Een kort, concreet Chengdu-moment op bamboestoelen; geen volle excursie. Was en dutjes krijgen ruimte.",
      pm: "Hotelpauze en eventueel nog een kort blok buiten. Leshan vervangt het hele rustige programma als iedereen goed uitgerust is; HSR en lokale transfers vooraf uitwerken. Bootzicht, leeftijdsregels en vaart eerst bevestigen.",
      eve: "Thee, eten en inpakken voor de korte Chongqing-stop.",
      baby: "Het theehuis is een kort uitstapje; teruggaan wanneer nodig. Voor Leshan bereid je een volledige reisdag voor.",
      backup:
        "Leshan vervalt bij regen of weinig energie. Ook Heming is vrijblijvend: de hele dag in het hotel is prima.",
      reserve:
        "Leshan-trein vanaf 28 maart als jullie kiezen; bootvoorwaarden en kinderzitje laten bevestigen.",
      cost: "Rustdag €10–25 aan uitjes; Leshan €80–160 voor het gezin als budget.",
    },
    {
      d: 16,
      city: "chongqing",
      kind: "trein",
      title: "Eén nacht in de neonstad.",
      sub: "Chengdu · Chongqing · Hongya Dong",
      am: "Uitchecken, korte HSR naar Chongqing. Exact aankomststation naar de chauffeur sturen.",
      pm: "Inchecken, lunch en een goede pauze. Niets vastleggen vóór het dutje.",
      eve: "Hongya Dong vanaf een rustig uitzichtpunt bij zonsondergang. Eten en op tijd terug voor de volgende reisdag.",
      baby: "De hoogteverschillen en trappen zijn groot. Draagzak handiger in de drukte; houd de avond kort.",
      backup:
        "Bij regen of vermoeidheid genieten van het rivierzicht in het hotel.",
      reserve:
        "Trein vanaf 29 maart. Beide transfers en vertrekstation voor morgen vastleggen.",
      cost: "Trein €12–30 per volwassene; uitzicht buiten gratis.",
    },
    {
      d: 17,
      city: "zhangjiajie",
      kind: "trein",
      title: "Naar de voet van de Avatarbergen.",
      sub: "Chongqing · Zhangjiajie West · Wulingyuan",
      am: "Hoteltransfer naar het op het ticket genoemde station. HSR naar Zhangjiajie West.",
      pm: "Vooraf geregelde privétransfer naar Wulingyuan, circa 45–75 minuten. Inchecken voor vier nachten.",
      eve: "Rustig eten. Met hotel de weersverwachting en volgorde van de komende bergdagen afstemmen.",
      baby: "Vandaag geen parkbezoek. Draagzak, regenjas en warme laag klaarleggen.",
      backup:
        "Het volledige programma D18–D20 mag op het weer worden aangepast.",
      reserve:
        "Trein vanaf 30 maart; transfer en tickets voor de gekozen parkroute.",
      cost: "Trein €25–45 per volwassene; transfer €25–45 per auto als budget.",
    },
    {
      d: 18,
      city: "zhangjiajie",
      kind: "natuur",
      title: "Tussen stenen torens & wolken.",
      sub: "Yuanjiajie · Bailong Elevator",
      am: "Via de oostelijke ingang en parkshuttle naar de Bailong-lift. Met een vroege start wachtrijen proberen te beperken.",
      pm: "Korte route langs Yuanjiajie-uitzichtpunten. Lunchpauze en tijdig via de gekozen route terug.",
      eve: "Eten in Wulingyuan. Weer en energie voor morgen bekijken.",
      baby: "Draagzak essentieel; liften en shuttles voorkomen niet alle trappen. Geen volledige wandelroute afdwingen.",
      backup:
        "Bij dichte mist deze dag ruilen met een lager gelegen wandeling of rust.",
      reserve:
        "Meerdaags parkentree en lift/shuttle volgens actueel ticketpakket vooraf laten controleren.",
      cost: "Totale Zhangjiajie-activiteitenpot voor D18–D20: €180–280 voor twee; geen dagprijs.",
    },
    {
      d: 19,
      city: "zhangjiajie",
      kind: "natuur",
      title: "Bergpanorama’s & een groene beek.",
      sub: "Tianzi Mountain · Golden Whip Stream",
      am: "Tianzi Mountain met kabelbaan als er goed zicht is. Kies een paar uitzichtpunten.",
      pm: "Golden Whip Stream: alleen een kort stuk van de beekroute. Een volledige combinatie kan lang worden; inkorten of één onderdeel laten vallen mag.",
      eve: "Vroege maaltijd en rust.",
      baby: "Draagzak voor de berg; buggy alleen op geschikte vlakke stukken. Houd ruimte voor regen en omkeren.",
      backup: "Bij mist alleen de beek, bij zware regen een hotelmiddag.",
      reserve:
        "Kabelbaan en parktoegang controleren; niet alle extra ritten zitten in het basiskaartje.",
      cost: "In de gezamenlijke Zhangjiajie-pot bij D18 opgenomen.",
    },
    {
      d: 20,
      city: "zhangjiajie",
      kind: "keuze",
      title: "Tianmen als bonus. Rust als basis.",
      sub: "Tianmen óf weerbuffer · Grand Canyon tweede keuze",
      am: "Eerst bepalen wat morgen haalbaar is. Bij een zeer vroege D21-trein: vandaag kort en rustig houden. Alleen bij goed zicht en voldoende energie Tianmen als één hoofdexcursie, met privétransfer vanuit Wulingyuan en apart ticket.",
      pm: "Voor Tianmen een route laten bevestigen met werkende kabelbaan en roltrappen, zodat de 999 treden niet verplicht zijn. Grand Canyon / glazen brug blijft een alternatief, met lagere prioriteit; kinderregels en draagzakbeleid eerst schriftelijk bevestigen.",
      eve: "Op tijd eten, inpakken en slapen. Ontbijtpakket en chauffeur voor D21 gereed; geen late show na een bergdag.",
      baby: "Tianmen kan een lange dag zijn met vervoer en wachtrijen. Een ontbrekende heldere parkdag van D18/D19 inhalen gaat vóór nog een nieuwe attractie.",
      backup:
        "D18/D19 inhalen als daar het weer tegenzat; anders hotel, dorp en rust.",
      reserve:
        "Tianmen is een apart ticket met tijdslot en routekeuze. Actuele kabelbaanstatus en roltraproute in 2027 laten bevestigen; niet afgaan op oude A/B/C-routebeschrijvingen.",
      cost: "In de gezamenlijke Zhangjiajie-pot; privétransfer naar Tianmen eventueel extra.",
    },
    {
      d: 21,
      city: "yangshuo",
      kind: "trein",
      title: "Een lange treindag. Een zachte landing.",
      sub: "Zhangjiajie · Guilin · Yangshuo",
      am: "Controleer eerst de vertrekopties. De 2026-referentie D3967 vertrekt 07:12 uit Zhangjiajie West: vanuit Wulingyuan betekent dat grofweg 04:30–05:00 hotelvertrek met stationsmarge. Als in 2027 een geschikte latere directe dienst rijdt, heeft die onze voorkeur. Ontbijtpakket en babyspullen klaar.",
      pm: "Circa 6u–8u30 trein als werkraming. Rechtstreeks heeft de voorkeur. Bij een overstap alleen een haalbare aansluiting: bij voorkeur hetzelfde station en 60–90 minuten marge. Changsha en Changsha South zijn verschillende stations; geen snelle stationswissel als basisplan.",
      eve: "Chauffeur bij het exacte Guilin-station. Naar het gekozen hotel in Yangshuo, eten en slapen. Inclusief auto’s kan dit een dag van 9–12 uur zijn.",
      baby: "Een eigen treinstoel overwegen en de zitplaatsen samen laten boeken. Geen sightseeing bij aankomst.",
      backup: "Bij late aankomst vooraf maaltijd en late check-in regelen.",
      reserve:
        "Tickets vanaf 3 april. Deze verbinding vóór andere binnenlandse ritten uitzoeken zodra het schema zichtbaar is. Vertrektijd, aankomststation, eventuele twee tickets, kinderzitje en late check-in bevestigen.",
      cost: "Trein €45–75 per volwassene; lange aankomsttransfer €55–90 per auto als budget.",
    },
    {
      d: 22,
      city: "yangshuo",
      kind: "rust",
      title: "Vandaag volgt de rivier het tempo.",
      sub: "Yulong River · wandelen & ontspannen",
      am: "Rustig ontbijt. Bij Mountain Retreat ligt de Yulong dichtbij; bij River View Hotel in Yangshuo-centrum eerst een korte transfer naar de Yulong afspreken. Daarna een klein rondje langs rivier en velden, geen fietstocht met Amélie.",
      pm: "Dutje in het hotel, daarna een terras of kleine wandeling. Geen bamboevlot met Amélie in het basisplan.",
      eve: "Eten bij de rivier en vroeg terug.",
      baby: "Vlotaanbieders hanteren onder meer minimumlengtes; een baby past hier niet in het standaardaanbod. Geniet als gezin vanaf de oever.",
      backup: "Bij regen: hotel, boekje, koffie en kijken naar de bergen.",
      reserve:
        "Geen verplicht tijdslot. Vanuit het stadshotel vervoer naar de Yulong plannen. Een volwassene kan eventueel alleen varen terwijl de ander bij Amélie blijft, na controle van de voorwaarden.",
      cost: "Oeverwandeling gratis; uitjespot €0–20, eventuele Yulong-transfer uit de vervoerpot en eten apart.",
    },
    {
      d: 23,
      city: "yangshuo",
      kind: "natuur",
      title: "Het landschap van het twintig-yuanbiljet.",
      sub: "Xingping · Li River",
      am: "Privétransfer naar Xingping. Wandel door het oude dorp en naar een bereikbaar rivieruitzicht.",
      pm: "Lunch en terug voor rust. Optioneel een grotere passagiersboot, alleen als babytoelating en passend reddingsvest bevestigd zijn; geen baby op een klein vlot.",
      eve: "Diner in het hotel of dicht in de buurt.",
      baby: "Basisprogramma vanaf de wal. Geen steile Xianggong-bergwandeling als vaste afspraak.",
      backup: "Bij regen korter naar Xingping, of deze dag ruilen met D24.",
      reserve:
        "Transfer met kinderzitje; eventuele bootkeuze vooraf laten controleren.",
      cost: "Privéauto + uitjes €60–110 voor het gezin als budget.",
    },
    {
      d: 24,
      city: "yangshuo",
      kind: "rust",
      title: "Een hele dag zonder moeten.",
      sub: "Volledige buffer- & familiedag",
      am: "Lang ontbijten. Geen wekker, geen gereserveerde excursie.",
      pm: "Was, spelen, dutje en een kleine wandeling als het droog is.",
      eve: "Laatste rustige avond in Yangshuo. Transfer naar Ping’an en bagageregeling bevestigen.",
      baby: "Deze dag is bewust leeg: herstellen is onderdeel van de reis.",
      backup:
        "Xingping alleen hiernaartoe schuiven als D23 door het weer verviel en iedereen zin heeft.",
      reserve: "Chauffeur voor morgen en Longji–Guilin West op D27 bevestigen.",
      cost: "Uitjes €0–20; eten apart.",
    },
    {
      d: 25,
      city: "longji",
      kind: "transfer",
      title: "Van rivierdal naar rijstterrassen.",
      sub: "Yangshuo · Longji · Ping’an",
      am: "Privétransfer naar Ping’an, reken circa 3u–4u vanaf Yangshuo plus stop en het laatste looptraject.",
      pm: "Bij de parking over op licht bagagevervoer/portier. Inchecken, eten en een korte wandeling bij het dorp.",
      eve: "Diner in het gastenhuis en een rustige avond.",
      baby: "Draagzak essentieel. De buggy helpt op de dorpstrappen weinig; grote bagage vooraf organiseren.",
      backup: "Bij veel regen direct naar het hotel en geen uitzichtwandeling.",
      reserve:
        "Transfer met kinderzitje, portier, exacte trapafstand en bagageopslag schriftelijk regelen.",
      cost: "Privéauto €90–150 per auto; entree en portier €30–55 voor het gezin als budget.",
    },
    {
      d: 26,
      city: "longji",
      kind: "natuur",
      title: "Wakker boven de velden.",
      sub: "Longji-rijstterrassen · korte dorpswandeling",
      am: "Korte wandeling naar een bereikbaar uitzichtpunt. Begin rustig en vraag het hotel welke paden droog en geschikt zijn.",
      pm: "Lunch en dutje. Later nog een klein rondje in Ping’an of een terras.",
      eve: "Laatste avond op mainland China. Chauffeur en treintijden nogmaals bevestigen.",
      baby: "Trappen, hoogteverschillen en natte stenen: draagzak en schoenen met grip. Geen grote trekking.",
      backup:
        "Bij mist genieten van dorp en gastenhuis. April garandeert geen ondergelopen spiegelterrassen; irrigatie verschilt per gebied en jaar.",
      reserve:
        "Hotel vraagt vóór D25 na hoe de velden er daadwerkelijk bij liggen; april is geen garantie op spiegelterrassen. Bij aanhoudend slecht weer kan twee nachten langer Yangshuo een alternatief zijn, als hotelannulering en de D27-transfer dat toelaten.",
      cost: "Entree in D25-pot opgenomen; lokaal extra’s €0–20.",
    },
    {
      d: 27,
      city: "hongkong",
      kind: "trein",
      title: "Rechtstreeks naar Hongkong.",
      sub: "Ping’an · Guilin West · West Kowloon",
      am: "Vroege privétransfer vanaf Ping’an naar Guilin West, circa 2u–3u afhankelijk van ophalen en weg. Plan ook portier en minimaal 60–90 minuten op het station.",
      pm: "Voorkeur: directe HSR naar Hong Kong West Kowloon, circa 3u10–3u20 als routebasis. Geen verplichte overstap in Guangzhou. Paspoorten bij de hand.",
      eve: "Grensformaliteiten bij aankomst, transfer naar hotel in Kowloon en rustig eten. Drie nachten Hongkong.",
      baby: "Dit is een volle transferdag. Geen avondtour vastleggen.",
      backup:
        "Als geen directe geschikte dienst beschikbaar is: ruime overstap via Guangzhou South of Shenzhen North uitwerken.",
      reserve:
        "Tickets vanaf 9 april; 2027-dienst bevestigen en alle reizigers correct registreren.",
      cost: "Trein €40–65 per volwassene; auto Longji–Guilin West €70–110 als budget.",
    },
    {
      d: 28,
      city: "hongkong",
      kind: "cultuur",
      title: "Van Star Ferry tot de Peak.",
      sub: "Hong Kong Island · Central · Victoria Peak",
      am: "Star Ferry naar Hong Kong Island en een korte wandeling door Central.",
      pm: "Hotelpauze of rustige lunch. Victoria Peak bij goed zicht; kies taxi/Peak Tram op basis van wachtrij en energie.",
      eve: "Diner en, als het past, even naar de verlichte haven.",
      baby: "Buggy voor promenade en veerboot; Central heeft hellingen en trappen. Houd de Peak als flexibel onderdeel.",
      backup:
        "Bij laaghangende wolken de Peak laten vallen en aan de haven blijven.",
      reserve:
        "Peak pas kiezen na weercheck en drukte-inschatting. Bij helder weer op D29 eventueel omwisselen met de rustige Kowloon-dag. Ferryregelingen en tarieven voor 2027 controleren.",
      cost: "Activiteiten en vervoer €35–80 voor het gezin als budget.",
    },
    {
      d: 29,
      city: "hongkong",
      kind: "rust",
      title: "Kowloon op z’n gemak.",
      sub: "Victoria Harbour · een rustige dag",
      am: "Rustig ontbijt en promenade bij Tsim Sha Tsui, met zicht op de skyline.",
      pm: "Dutje, koffie en een klein rondje Kowloon als basis. Extra keuze bij helder weer én veel energie: Ngong Ping 360, Po Lin en de Grote Boeddha op Lantau, ter vervanging van de hele Kowloon-dag. Geen combinatie met Peak, Tai O of Disneyland.",
      eve: "Laatste volledige hotelavond. Een fijn diner is genoeg.",
      baby: "Kowloon beschermt het ritme vóór de nachtvlucht. Lantau is een grotere uitstap met vervoer en wachtrijen; de 268 treden naar het Boeddhaplatform hoeven niet in het plan.",
      backup: "Bij regen een winkelcentrum, museum naar keuze of hotelmiddag.",
      reserve:
        "Bagageopslag en late checkout voor morgen bevestigen. Alleen bij keuze voor Lantau: actuele kabelbaanwerking, baby-/buggyregels, terugreis en totale offerte controleren.",
      cost: "Kowloon: uitjes €0–25, eten apart. Optioneel Ngong Ping heeft extra kabelbaan-/vervoerkosten: actuele gezinsprijs eerst opvragen en bij Budget invullen.",
    },
    {
      d: 30,
      city: "hongkong",
      kind: "vlucht",
      title: "Nog één dag. Dan vliegen we naar huis.",
      sub: "Hotelcheckout · HKG 23:55 · Frankfurt",
      am: "Ontbijt en uitchecken volgens het hotelbeleid. Bagage bij het hotel opslaan; essentials voor Amélie in de dagtas.",
      pm: "Een rustige wandeling of een vooraf geboekte dagkamer/late checkout. Daar kan Amélie nog slapen en kunnen jullie opfrissen.",
      eve: "Bagage ophalen. Vertrek met ruime marge naar HKG; mik rond 20:30–20:55 op de luchthaven. Vlucht om 23:55 naar Frankfurt met Cathay Pacific.",
      baby: "Dagkamer of late checkout is een waardevolle extra voor de lange dag. Kinderzitje voor de vlucht en eigen stoel opnieuw bevestigen.",
      backup:
        "Bij regen/vermoeidheid hotel of dagkamer. Geen attractie met vaste eindtijd.",
      reserve:
        "HKG-transfer met kinderzitje of Airport Express-route uitwerken. Bagageopslag/dagkamer vooraf bevestigen.",
      cost: "Airporttransfer €35–70 als budget; late checkout/dagkamer apart.",
      sleep: "In het vliegtuig",
    },
    {
      d: 31,
      city: "reis",
      kind: "vlucht",
      title: "Thuis op Koningsdag.",
      sub: "Frankfurt · Amsterdam · aankomst 10:35",
      am: "Overstap in Frankfurt op Lufthansa. Exacte aansluiting en gate volgens het ticket. Aankomst AMS 10:35 lokale tijd.",
      pm: "Naar huis, uitpakken kan later. Geen afspraken plannen.",
      eve: "Rustig in het eigen ritme komen.",
      baby: "Ook op FRA–AMS moet het eigen zitje door de uitvoerende maatschappij zijn geaccepteerd.",
      backup:
        "Bij aansluitingsproblemen de luchtvaartmaatschappij laten omboeken; ruimte houden voor herstel.",
      reserve: "Ophalen vanaf Schiphol of taxi met passend kinderzitje.",
      cost: "Vervoer naar huis apart van het landbudget.",
      sleep: "Thuis",
    },
  ],
  videos: [
    {
      id: "-uJSab801Z4",
      title: "China vanuit de trein",
      area: "Shanghai · Beijing",
      credit: "Simon Andersen · video uit de spoor27-route",
      note: "First Class-video voor sfeer en treinervaring; ons budget rekent met 2e klas en een rit via Hangzhou.",
    },
    {
      id: "siFRKIJHbWg",
      title: "Tussen de Avatarbergen",
      area: "Zhangjiajie · Wulingyuan",
      credit: "FOLLOW ME · Hunan Province",
      note: "Een voorproefje van de bergen; de dagindeling passen jullie aan op het weer.",
    },
    {
      id: "86y_JC-jirM",
      title: "Het mooiste groen van China",
      area: "Yangshuo · Li River",
      credit: "Asia Odyssey Travel · Guilin",
      note: "Landschapsinspiratie. De vlotactiviteiten in de video zijn geen babyprogramma.",
    },
  ],
};
